### ISSUE TITLE
Дополнение инструкции по установке

### ISSUE THREAD

**Issue by valsha** [BuyOwnEx/BOEClient#29]
перед
```
Generate a new application key

php artisan key:generate
```

надо наверно добавить 

`sudo composer install --ignore-platform-reqs`

потому что 

`sudo composer update --no-scripts`

не работает, из за

` - phpunit/phpunit 8.5.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.`

хоть у вас и указано в composer.json 

```
"require": {
    "^7.2.5|^7.3|^8.0",
    .....
},
```

**Comment by BuyOwnEx** [comment]
Please check the official laravel 7.x installation guide for server requirements before you start. Official Documentation

In this official documentation you can see server requirements such as:

PHP >= 7.2.5
BCMath PHP Extension
Ctype PHP Extension
Fileinfo PHP extension
JSON PHP Extension
Mbstring PHP Extension
OpenSSL PHP Extension
PDO PHP Extension
Tokenizer PHP Extension
XML PHP Extension

The last one includes ext-dom

**Comment by valsha** [comment]
Ну 7я версия Laravel работает без проблем и с 8 версией PHP
с учетом даже того что в том же composer.json указано "^7.2.5|^7.3|^8.0",

**Comment by BuyOwnEx** [comment]
I will check for installation with php v. 8.0
The error
`phpunit/phpunit 8.5.x-dev requires ext-dom * -> the requested PHP extension dom is missing from your system.`
tell us simply install dom php Extension, right?

**Comment by valsha** [comment]
yes, php extension is installed.
the problem is here i think
`- phpunit/phpunit 8.5.9 requires php ^7.2 -> your PHP version (8.0.7) does not satisfy that requirement.`

**Comment by BuyOwnEx** [comment]
Yes, will add

`sudo composer install --ignore-platform-reqs`

but only, I guess, for php v. 8.0
