### ISSUE TITLE
Blank page at http://127.0.0.1:8000 after setting everything up locally

### ISSUE THREAD

**Issue by jordanurbs** [BuyOwnEx/BOEClient#31]
No Laravel or composer errors in any of the steps; but completely blank white page on load after initial setup. Following directions exactly.

**Comment by BuyOwnEx** [comment]
Please, provide console logs and logs from the directory ./storage/logs

**Comment by BuyOwnEx** [comment]
Also, add this line
`MIX_WS_SERVER=wss://demo.buyownex.com/connection/websocket`
into .env file

**Comment by jordanurbs** [comment]
Adding the `MIX_WS_SERVER `line did not help

Looks like this is the error: local.ERROR: `The Mix manifest does not exist.`

**Comment by BuyOwnEx** [comment]
try
`npm install`
and then
`npm run dev`
or
`npm run prod`

**Comment by jordanurbs** [comment]
Can't `npm run`

debug.log says:

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node@14/14.17.3/bin/node',
1 verbose cli   '/usr/local/opt/node@14/bin/npm',
1 verbose cli   'run',
1 verbose cli   'prod'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.3
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle boeclient@1.0.1~preprod: boeclient@1.0.1
6 info lifecycle boeclient@1.0.1~prod: boeclient@1.0.1
7 verbose lifecycle boeclient@1.0.1~prod: unsafe-perm in lifecycle true
8 verbose lifecycle boeclient@1.0.1~prod: PATH: /usr/local/Cellar/node@14/14.17.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Volumes/Scratchy 2/Nextcloud/Jordan/BOEClient-master/node_modules/.bin:/usr/local/opt/node@14/bin:/Users/jordan/.nvm/versions/node/v6.12.0/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/usr/local/decred:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jordan/Go/bin
9 verbose lifecycle boeclient@1.0.1~prod: CWD: /Volumes/Scratchy 2/Nextcloud/Jordan/BOEClient-master
10 silly lifecycle boeclient@1.0.1~prod: Args: [ '-c', 'npm run production' ]
11 silly lifecycle boeclient@1.0.1~prod: Returned: code: 2  signal: null
12 info lifecycle boeclient@1.0.1~prod: Failed to exec prod script
13 verbose stack Error: boeclient@1.0.1 prod: `npm run production`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/Cellar/node@14/14.17.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node@14/14.17.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid boeclient@1.0.1
15 verbose cwd /Volumes/Scratchy 2/Nextcloud/Jordan/BOEClient-master
16 verbose Darwin 20.5.0
17 verbose argv "/usr/local/Cellar/node@14/14.17.3/bin/node" "/usr/local/opt/node@14/bin/npm" "run" "prod"
18 verbose node v14.17.3
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 2
22 error boeclient@1.0.1 prod: `npm run production`
22 error Exit status 2
23 error Failed at the boeclient@1.0.1 prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true`

**Comment by jordanurbs** [comment]
`npm run` does not work

debug log:

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node@14/14.17.3/bin/node',
1 verbose cli   '/usr/local/opt/node@14/bin/npm',
1 verbose cli   'run',
1 verbose cli   'prod'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.3
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle boeclient@1.0.1~preprod: boeclient@1.0.1
6 info lifecycle boeclient@1.0.1~prod: boeclient@1.0.1
7 verbose lifecycle boeclient@1.0.1~prod: unsafe-perm in lifecycle true
8 verbose lifecycle boeclient@1.0.1~prod: PATH: /usr/local/Cellar/node@14/14.17.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/xx/xxx/BOEClient-master/node_modules/.bin:/usr/local/opt/node@14/bin:/xx/xxx/.nvm/versions/node/v6.12.0/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/usr/local/decred:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/xxx/Go/bin
9 verbose lifecycle boeclient@1.0.1~prod: CWD: /xx/xxx//BOEClient-master
10 silly lifecycle boeclient@1.0.1~prod: Args: [ '-c', 'npm run production' ]
11 silly lifecycle boeclient@1.0.1~prod: Returned: code: 2  signal: null
12 info lifecycle boeclient@1.0.1~prod: Failed to exec prod script
13 verbose stack Error: boeclient@1.0.1 prod: `npm run production`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/Cellar/node@14/14.17.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node@14/14.17.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid boeclient@1.0.1
15 verbose cwd /xx/xxx//BOEClient-master
16 verbose Darwin 20.5.0
17 verbose argv "/usr/local/Cellar/node@14/14.17.3/bin/node" "/usr/local/opt/node@14/bin/npm" "run" "prod"
18 verbose node v14.17.3
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 2
22 error boeclient@1.0.1 prod: `npm run production`
22 error Exit status 2
23 error Failed at the boeclient@1.0.1 prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]`

**Comment by BuyOwnEx** [comment]
please, provide screenshot after executing command `npm run dev` (not debug log)

**Comment by jordanurbs** [comment]
![Screen Shot 2021-08-10 at 1 59 23 PM](https://user-images.githubusercontent.com/44348964/128934445-2d8e65e0-6af7-418c-a8a1-bc8e4600c780.png)

**Comment by BuyOwnEx** [comment]
https://github.com/NativeScript/NativeScript/issues/9493

Guess, running `npm i vue-loader` will solve your problem

**Comment by jordanurbs** [comment]
Thank you :)
