### ISSUE TITLE
Its not work

### ISSUE THREAD

**Issue by AranyaPandit** [BuyOwnEx/BOEClient#32]
Issuse 
![Screenshot (1)](https://github.com/BuyOwnEx/BOEClient/assets/129489710/3236d437-14f0-4c10-9281-2f2508cd2164)

**Comment by BuyOwnEx** [comment]
Please, attach your .env file

**Comment by AranyaPandit** [comment]
[.env.zip](https://github.com/BuyOwnEx/BOEClient/files/14034296/default.env.zip)

**Comment by BuyOwnEx** [comment]
Try again
